### ISSUE TITLE
I may have found the reason why CUDA cannot be used :)

### ISSUE THREAD

**Issue by Sighnor** [QuentinVacher-rl/SoftActorCritic-in-Cpp-using-LibTorch#1]
The inability to use CUDA may not be a compatibility issue, but that some tensors have not been moved to CUDA. I called the to(device) method on some tensors, and then the program can use GPU training correctly.

**Comment by QuentinVacher-rl** [comment]
Hey,
Great thanks! If I remember correctly, I did this in the beginning, but removed the to(device) because it was not working.
I had problems during compilation because the torch library made some function of the json library disappear. 
Did you keep the jsoncpp while it was working?

**Comment by Sighnor** [comment]
Yes, I tested the loadParametersFromJson function, and it ran correctly and assigned values to the SACParameters class. I linked the libtorch library in the project properties of VS2022, and I did not encounter any compilation issues when generating the project

**Comment by QuentinVacher-rl** [comment]
Okay great then ! I will update the code when I have time thank you very much :)
